creacion de comparacion del nit con la bd
PedroOspina17/Reciplastk pull request #12
Opened 2024-05-09 21:24 UTC by david0110

2024-05-29 17:48 UTC, PedroOspina17 requested changes
Just a couple of comments, please adjust acordingly.

2024-05-29 17:48 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Controllers/CustomerController.cs
> +        [HttpGet("Show all customers")]
Remember, what you put inside the "" is the Value that goes in the URL. Do not include spaces or strange values. 
```suggestion
        [HttpGet("ShowAll")]
```

2024-05-29 17:48 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Controllers/CustomerController.cs
> +        [HttpGet("Show a customer")]
```suggestion
        [HttpGet("Find")]
```

2024-05-29 17:48 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Controllers/CustomerController.cs
> +        [HttpPost("Create customer")]
```suggestion
        [HttpPost("Create")]
```

2024-05-29 17:48 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Controllers/CustomerController.cs
> +        [HttpPost("Edit customer")]
```suggestion
        [HttpPost("Edit")]
```

2024-05-29 17:48 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Controllers/CustomerController.cs
> +        [HttpDelete("Delete customer")]
```suggestion
        [HttpDelete("Delete")]
```

2024-05-29 17:48 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Services/CustumerService.cs
> +    public class CustumerService
The name is wrong. 
```suggestion
    public class CustomerService
```

2024-05-29 17:48 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Services/CustumerService.cs
> +        private Customer CustomerById(int? customerId)
Remember to name the methods starting with a verb. 
```suggestion
        private Customer GetCustomerById(int? customerId)
```

2024-05-29 17:48 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Services/CustumerService.cs
> +        private Customer CustomerByNit(String customerNit)
```suggestion
        private Customer GetCustomerByNit(String customerNit)
```

2024-05-29 17:48 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Services/CustumerService.cs
> +                response.StatusMessage = "The customer was not created";
Remember to be more specific with the response messages. Also remember, the UI and messages that are meant to be shown in the UI are in Spanish for now. 
```suggestion
                response.StatusMessage = "Ya existe otro cliente con el NIT indicado";
```

2024-05-29 17:48 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Services/CustumerService.cs
> +                response.StatusMessage = "The customer was not found";
```suggestion
                response.StatusMessage = "No existe ningun cliente con el Id especificado";
```

2024-05-29 17:48 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Services/CustumerService.cs
> +                response.StatusMessage = "The customer was deleted successfully";
```suggestion
                response.StatusMessage = "El cliente fue eliminado exitosamente";
```

2024-05-29 17:48 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Services/CustumerService.cs
> +                response.StatusMessage = "The customer was not deleted";
```suggestion
                response.StatusMessage = "No se encontró ningún cliente con el Id especificado";
```

2024-07-02 12:06 UTC, david0110 commented
ya fueron realizadas todas las correciones

2024-07-02 12:07 UTC, closed without merging