Customer module
PedroOspina17/Reciplastk pull request #16
Opened 2024-07-02 12:12 UTC by david0110

EL modulo de clientes, tanto el BackEnd como el FrontEnd fueron terminadas, atento a reviciones y correciones de codigo.

2024-08-09 05:07 UTC, PedroOspina17 requested changes
Congratulations !!! This is an amazing code 
Just a few small comment but everything is as expected. Nice job

2024-08-09 05:07 UTC, PedroOspina17 commented on Front/src/app/components/admin/add-edit-customer/add-edit-customer.component.html
> +                            formCustomer.get('lastNsame')?.hasError('required') &&
This property is misspelled. 
```suggestion
                            formCustomer.get('lastName')?.hasError('required') && 
```

2024-08-09 05:07 UTC, PedroOspina17 commented on Front/src/app/services/customer.service.ts
> +  ServiceEndpoint: string = `${AppConfig.API_URL}`;
Concatenate the controller name here and avoid it in every method.
```suggestion
  ServiceEndpoint: string = `${AppConfig.API_URL}/api/Customer`;
```

2024-08-09 05:07 UTC, PedroOspina17 commented on Front/src/app/services/customer.service.ts
> +    return this.http.get<HttpResponseModel>(this.ServiceEndpoint+'/api/Customer/ShowAllCustomers')
Apply this for all the rest of the methods
```suggestion
    return this.http.get<HttpResponseModel>(this.ServiceEndpoint+'/ShowAllCustomers')
```

2024-08-13 21:54 UTC, PedroOspina17 commented
@david0110 Remember to store all the database scripts in the `Reciplastk\DB` folder, you can

2024-08-13 22:15 UTC, PedroOspina17 requested changes

2024-08-13 22:15 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Services/CustomerService.cs
> +            var customer = GetById((int?)customerid);
This conversion is not necessary, it is better to avoid the nullable in the GetById Method.

2024-08-13 22:15 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Services/CustomerService.cs
> +        private Customer GetById(int? customerId)
why do you need this parameter to be nullable ? (int?)

2024-08-13 22:15 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Services/CustomerService.cs
> +            var customer = GetByNit(customerViewModel.nit);
Make sure the customer does not exist with the same nit. 
```suggestion
            var customer = GetByNit(customerViewModel.nit);
            if(customer != null) // Customer exists with the same id
            {
             return new HttpResponseModel() {wasSuccessfull = false; message = "Ya existed un cliente con este mismo NIT"};
            }
```

2024-08-13 22:15 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Services/CustomerService.cs
> +                response.StatusMessage = "The customer was not found";
Messages to the user must be in spanish.

2024-08-13 22:15 UTC, PedroOspina17 commented on Front/src/app/components/admin/add-edit-customer/add-edit-customer.component.html
> +                            formCustomer.get('lastNsame')?.touched"
Still have error in the field name.

2024-08-13 22:15 UTC, PedroOspina17 commented on Front/src/app/components/admin/add-edit-customer/add-edit-customer.component.html
> +                        <label for="Nombre" class="control-label">Nombre</label>
form Ids must be in english. 
```suggestion
                        <label for="Name" class="control-label">Nombre</label>
                        <input type="text" class="form-control mt-2" placeholder="Nombre" id="Name" formControlName="name">
```

2024-08-13 22:15 UTC, PedroOspina17 commented on Front/src/app/components/admin/add-edit-customer/add-edit-customer.component.html
> +                        <label for="Nombre" class="control-label">Apellido</label>
Label for should be pointing to the input id. 
```suggestion
                        <label for="Lastname" class="control-label">Apellido</label>
```

2024-08-13 22:15 UTC, PedroOspina17 commented on Front/src/app/components/admin/add-edit-customer/add-edit-customer.component.html
> +                        <input type="text" class="form-control mt-2" placeholder="Apellido" id="Apellido" formControlName="lastname">
Field id should be in english. 
```suggestion
                        <input type="text" class="form-control mt-2" placeholder="Apellido" id="Lastname" formControlName="lastname">
```

2024-08-13 22:15 UTC, PedroOspina17 commented on Front/src/app/components/admin/add-edit-customer/add-edit-customer.component.html
> +                        <label for="Nombre" class="control-label">Direccion</label>
Same issue with the for attribute for all the rest. It should be pointing to the input id and the input id should be in English, only visible text for the user will be in Spanish.
```suggestion
                        <label for="Address" class="control-label">Direccion</label>
```

2024-08-13 22:15 UTC, PedroOspina17 commented on Front/src/app/components/admin/shipment/shipment.component.html
Delete this file, this is not part of customers module.

2024-08-14 14:09 UTC, david0110 commented on Back/Reciplastk.Gateway/Services/CustomerService.cs
> +        private Customer GetById(int? customerId)
I put the nullable in the ViewModel, cause in the front end not always it will send a id

2024-08-20 22:01 UTC, PedroOspina17 approved these changes
Amazing job !

2024-08-20 22:02 UTC, merged