Product prices module
PedroOspina17/Reciplastk pull request #28
Opened 2024-11-27 19:58 UTC by david0110

2025-01-16 02:03 UTC, PedroOspina17 requested changes
Amazing job !! 
Just a bunch of small details, please fix them and ask for review again.

2025-01-16 02:03 UTC, PedroOspina17 commented on Front/src/app/models/ProductPriceModel.ts
> +    ShowHistory?: boolean;
you are mixing lower case and upper case. pay attention on this and fix it.

2025-01-16 02:03 UTC, PedroOspina17 commented on Front/src/app/models/RoleParams.ts
> +export class RoleParams{
aren't you able to reuse the RoleViewModel ? this one is exactly the same as the other one. it is ok to have it nullable for the list functionality

2025-01-16 20:12 UTC, david0110 commented on Front/src/app/components/admin/copy-customer-prices/copy-customer-prices.component.ts
> +    const copyCustomerPricesViewModel: CopyCustomerPricesViewModel = {
I dont understand what happend or what is wrong

2025-01-20 20:55 UTC, PedroOspina17 approved these changes

2025-01-20 20:55 UTC, PedroOspina17 commented on Back/Reciplastk.Gateway/Services/ProductsService.cs
> +                    else
All this else block is not necessary. Remove it

2025-01-20 20:55 UTC, merged